// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'cards/card_model_base_test.dart' as cards_card_model_base_test;

void main() {
  cards_card_model_base_test.main();
}
